const NotificationType = {
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  NEW_MESSAGE: 'NEW_MESSAGE',
  REMINDER: 'REMINDER'
};

module.exports = NotificationType;